### ISSUE TITLE
Implement front-end moderator dashboard page

### ISSUE THREAD

**Issue by thepbordin** [2110503TACEDT66/cedt-se-project-mewing-komkom#14]
# Moderator dashboard for user management should include
- styling like this [figma design](https://www.figma.com/file/uGTHI90OgPoVaMoRjzDf3g/co-working-space?type=design&node-id=59-138&mode=design&t=DvW3QJaJPmW7UdXr-4)
- implemented with the backend endpoints (wait for #8 to completed)
  - list all current admins (co-working spaces' admins) 
  - delete account
  -  edit user account information
  - create new admin account

**Comment by TENet1010** [comment]
okay krub implement create new admin in process Now
