### ISSUE TITLE
All method should named as camelCase

### ISSUE THREAD

**Issue by thepbordin** [2110503TACEDT66/cedt-se-project-mewing-komkom#6]
please fix all the method violate naming rules

**Comment by RatchanonMo** [comment]
very agree

**Comment by RatchanonMo** [comment]
![giphy (11)](https://github.com/2110503TACEDT66/cedt-se-project-mewing-komkom/assets/69392334/4e889871-f8fd-4dce-80d1-0366822d05a7)
