### ISSUE TITLE
Implement back-end endpoints for moderator

### ISSUE THREAD

**Issue by TENet1010** [2110503TACEDT66/cedt-se-project-mewing-komkom#8]
"We need to implement backend endpoints for moderators with the following functionalities:

- Only users with the 'moderator' role should be able to retrieve a` list of all users`.
- Moderators should be able to `edit` user information.
- Moderators should be able to `delete` user accounts."

**Comment by thepbordin** [comment]
Another route required
## GET `api/v1/user/generateAdmin` create a new admin account 
  - generate a random password
  - required password changes on the first login
  - return the new admin account with the password
